version: '3.8'
services:
  gotrue:
    image: gotrue
    container_name: gotrue
    restart: always
    ports:
      - '9999:9999'
    env_file:
      - gotrue.env
    networks:
      - restapi_network
    depends_on:
      - postgres
    
  postgres:
    image: gotrue_postgres
    container_name: gotrue_postgres
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - gotrue_postgres_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=postgres
      - DB_NAMESPACE=auth
    networks:
      - restapi_network
  app: 
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: app
    restart: always
    env_file:
      - .env
    ports:
      - 4000:4000
    networks:
      - restapi_network
    depends_on:
      - gotrue

networks:
  restapi_network: