apiVersion: apps/v1
kind: Deployment
metadata:
  name: flex-rest-api
  namespace: default
  labels:
    environment: production
    app: flex-rest-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flex-rest-api
  template:
    metadata:
      labels:
        environment: production
        app: flex-rest-api
    spec:
      containers:
        - name: flex-rest-api-container
          image: umeshdani/flex-rest-api:latest
          ports:
            - containerPort: 8080
          env:
            - name: API_EXTERNAL_URL
              valueFrom:
                secretKeyRef:
                  name: flex-rest-api-secret
                  key: API_EXTERNAL_URL
            - name: DP_SITE_URL
              valueFrom:
                secretKeyRef:
                  name: flex-rest-api-secret
                  key: DP_SITE_URL
            - name: DP_DB_URL
              valueFrom:
                secretKeyRef:
                  name: flex-rest-api-secret
                  key: DP_DB_URL
            - name: DP_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: flex-rest-api-secret
                  key: DP_JWT_SECRET
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: flex-rest-api-secret
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: flex-rest-api-secret
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: flex-rest-api-secret
                  key: AWS_REGION
            - name: AWS_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: flex-rest-api-secret
                  key: AWS_BUCKET_NAME
